// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3rsaPUazoAMheyAzAuo_Ls2dxgKgUeNw',
    appId: '1:875334233564:web:d96887b991170c697d7319',
    messagingSenderId: '875334233564',
    projectId: 'spotify-c1e06',
    authDomain: 'spotify-c1e06.firebaseapp.com',
    storageBucket: 'spotify-c1e06.firebasestorage.app',
    measurementId: 'G-E2EBCEGGZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbH3Mt3PVUi8USNIjkEHwEbzVJDvLDjc',
    appId: '1:875334233564:android:e29eb799facef7287d7319',
    messagingSenderId: '875334233564',
    projectId: 'spotify-c1e06',
    storageBucket: 'spotify-c1e06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIsdVKXK6qMczfPifOigrmFO9i2VMx8O0',
    appId: '1:875334233564:ios:261066ec00fe201b7d7319',
    messagingSenderId: '875334233564',
    projectId: 'spotify-c1e06',
    storageBucket: 'spotify-c1e06.firebasestorage.app',
    iosBundleId: 'com.example.appNghenhac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIsdVKXK6qMczfPifOigrmFO9i2VMx8O0',
    appId: '1:875334233564:ios:261066ec00fe201b7d7319',
    messagingSenderId: '875334233564',
    projectId: 'spotify-c1e06',
    storageBucket: 'spotify-c1e06.firebasestorage.app',
    iosBundleId: 'com.example.appNghenhac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3rsaPUazoAMheyAzAuo_Ls2dxgKgUeNw',
    appId: '1:875334233564:web:fd5b501a029181417d7319',
    messagingSenderId: '875334233564',
    projectId: 'spotify-c1e06',
    authDomain: 'spotify-c1e06.firebaseapp.com',
    storageBucket: 'spotify-c1e06.firebasestorage.app',
    measurementId: 'G-BF4RHJ2Q70',
  );

}