// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyW9zog98Io2SRO5c2tRWV-_fIyppeAw',
    appId: '1:462126169315:web:bfbfe5567bae19d15259d6',
    messagingSenderId: '462126169315',
    projectId: 'spotify-890c4',
    authDomain: 'spotify-890c4.firebaseapp.com',
    storageBucket: 'spotify-890c4.firebasestorage.app',
    measurementId: 'G-BBQ9YKL5F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kNG52vYviEZb_NResz-Jkh0VojMaw9A',
    appId: '1:462126169315:android:c1a49b563884f3725259d6',
    messagingSenderId: '462126169315',
    projectId: 'spotify-890c4',
    storageBucket: 'spotify-890c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Jwd8rs3X8vA6K0DcD2XMStE9ODM6N2Y',
    appId: '1:462126169315:ios:e3eaf29fc3793df45259d6',
    messagingSenderId: '462126169315',
    projectId: 'spotify-890c4',
    storageBucket: 'spotify-890c4.firebasestorage.app',
    iosBundleId: 'com.example.appNghenhac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Jwd8rs3X8vA6K0DcD2XMStE9ODM6N2Y',
    appId: '1:462126169315:ios:e3eaf29fc3793df45259d6',
    messagingSenderId: '462126169315',
    projectId: 'spotify-890c4',
    storageBucket: 'spotify-890c4.firebasestorage.app',
    iosBundleId: 'com.example.appNghenhac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGyW9zog98Io2SRO5c2tRWV-_fIyppeAw',
    appId: '1:462126169315:web:ff378efb349b72f95259d6',
    messagingSenderId: '462126169315',
    projectId: 'spotify-890c4',
    authDomain: 'spotify-890c4.firebaseapp.com',
    storageBucket: 'spotify-890c4.firebasestorage.app',
    measurementId: 'G-QM1LKQW9YJ',
  );
}
